### ISSUE TITLE
Create and add video instructions for ordinary users.

### ISSUE THREAD

**Issue by My12123** [Atharva-Phatak/Manga-Colorizer#16]
- [ ] Create and add video instructions for ordinary users.

**Comment by Keiser04** [comment]
idk i event cant open the app, but dont train whit this,

**Comment by My12123** [comment]
@Keiser04 To install, I wrote the code https://github.com/Atharva-Phatak/Manga-Colorizer/pull/11
It's a good idea not to suffer with this repository since the author does not respond.
