### ISSUE TITLE
How to install for windows?

### ISSUE THREAD

**Issue by My12123** [Atharva-Phatak/Manga-Colorizer#4]
- [ ] Detailed instructions for Windows.

**Comment by Atharva-Phatak** [comment]
install python and create a venv

**Comment by My12123** [comment]
Write in more detail.

**Comment by Atharva-Phatak** [comment]
This will be helpful : https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/

**Comment by My12123** [comment]
@Atharva-Phatak 
Step-by-step instructions would be better.
