### ISSUE TITLE
What is the version of PyTorch?

### ISSUE THREAD

**Issue by My12123** [Atharva-Phatak/Manga-Colorizer#5]
What is the version of PyTorch?

**Comment by Atharva-Phatak** [comment]
There's a requirement.txt  which has dependencies. TorchFlare is probably broken because I did not have time to maintain it.

**Comment by My12123** [comment]
![2023-10-25_22-00-47](https://github.com/Atharva-Phatak/Manga-Colorizer/assets/49092250/1094cb69-c39e-457e-9029-a4a7986a1022)
The PyTorch version is not specified. I will use the latter for GPU. I use Windows.

**Comment by Atharva-Phatak** [comment]
Torchflare will install the version of pytorch 😄
